/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.
*/
public class DifferenceBetweenTwoStrings {
    public char findTheDifference(String s, String t) {
        
        int charTot = (int)t.charAt(s.length());
        
        for(int i=0; i< s.length(); i++){
            
            charTot -= (int)s.charAt(i);
            charTot += (int)t.charAt(i);
        }
        
        return (char)charTot;
    }
}